# API Keys, sensitive data, and secrets should not be stored in your repository
#gitleaks is a popular tool for scanning your code for secrets and sensitive data. This workflow uses the trufflehog action to run gitleaks on your code and report any findings.

name: Secrets Scan

on:
  workflow_call:

jobs:
  secrets_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for gitleaks to work properly

      - name: Run gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #github token is automatically provided by GitHub Actions, it allows the action to comment on pull requests or create issues if secrets are found
